name: CI

on:
  # Run when action performed on main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manually allowed as well
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: mb64-parser
  PROJECT_PATH: ./

jobs:
  build:
    name: web
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          lfs: true

      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        
      - name: web_build
        run: |
          mkdir -v -p html/
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../html/index.html
          
      - name: upload_artifact
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: ./html/

      - name: install_rsync
        run: |
          apt-get update && apt-get install rsync
      
      - name: deploy_ghp
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: ./html/
